In [ ]:
# Numpy-Tensor Exercises #

In [ ]:
# Increasing the Cell Width of Jupyter Notebook

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [ ]:
# Importing Libraries

import torch
import numpy as np

In [ ]:
# Numpy Number

x = np.array(4)
print(f"x: {x}\n")
print(f"x.shape: {x.shape}")

x: 4

x.shape: ()


In [ ]:
# Converting a Numpy Number to a Torch Number

y = torch.from_numpy(x)
print(f"y: {y}\n")
print(f"y.shape: {y.shape}")

y: 4

y.shape: torch.Size([])


In [ ]:
# Torch Number

b = torch.tensor(2)
print(f"b: {b}\n")
print(f"b.shape: {b.shape}")

b: 2

b.shape: torch.Size([])


In [ ]:
# Converting a Torch Number Back to a Numpy Number

a = b.numpy()
print(f"a: {a}\n")
print(f"a.shape: {a.shape}")

a: 2

a.shape: ()


In [ ]:
# Numpy Array

n = np.array([[1, 2], [3, 4.]])
print(f"n:\n{n}\n")
print(f"n.shape:\n{n.shape}")

n:
[[1. 2.]
 [3. 4.]]

n.shape:
(2, 2)


In [ ]:
# Converting a Numpy Array to a Torch Tensor

t = torch.from_numpy(n)
print(f"t:\n{t}\n")
print(f"t.shape:\n{t.shape}")

t:
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

t.shape:
torch.Size([2, 2])


In [ ]:
# Numpy Array and Torch Tensor Have Similar Data Types

print(f"n.dtype: {n.dtype}\n")
print(f"t.dtype: {t.dtype}")

n.dtype: float64

t.dtype: torch.float64


In [ ]:
# Converting a Torch Tensor Back to a Numpy Array

m = t.numpy()
print(f"m:\n{m}\n")
print(f"m.shape:\n{m.shape}")

m:
[[1. 2.]
 [3. 4.]]

m.shape:
(2, 2)


In [ ]:
################################################

In [ ]:
# Row

t1 = torch.tensor([1., 2, 3, 4])
print(f"t1:\n{t1}\n")
print(f"t1.shape:\n{t1.shape}")

t1:
tensor([1., 2., 3., 4.])

t1.shape:
torch.Size([4])


In [ ]:
# Column

t2 = torch.tensor([[5.], [6], [7], [8]])
print(f"t2:\n{t2}\n")
print(f"t2.shape:\n{t2.shape}")

t2:
tensor([[5.],
        [6.],
        [7.],
        [8.]])

t2.shape:
torch.Size([4, 1])


In [ ]:
# Matrix

t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
print(f"t3:\n{t3}\n")
print(f"t3.shape:\n{t3.shape}")

t3:
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

t3.shape:
torch.Size([3, 2])


In [ ]:
# 3-Dimensional Array

t4 = torch.tensor([ [[11, 12, 13],
                     [13, 14, 15]],

                    [[15, 16, 17],
                     [17, 18, 19.]] ])
print(f"t4:\n{t4}\n")
print(f"t4.shape:\n{t4.shape}")

t4:
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

t4.shape:
torch.Size([2, 2, 3])


In [ ]:
# Creating Tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = x * w + b
print("y:", y)

y: tensor(17., grad_fn=<AddBackward0>)


In [ ]:
# Computing Derivatives of y

y.backward()

In [ ]:
# Displaying Gradients

print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
# Creating a Tensor with a Fixed Value for Every Element

t6 = torch.full([3, 2], 42)
print(f"t6:\n{t6}\n")
print(f"t6.shape:\n{t6.shape}")

t6:
tensor([[42, 42],
        [42, 42],
        [42, 42]])

t6.shape:
torch.Size([3, 2])


In [ ]:
# Concatenation of Two Tensors: t3 & t6

t7 = torch.cat([t3, t6])
print(f"t7:\n{t7}\n")
print(f"t7.shape:\n{t7.shape}")

t7:
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

t7.shape:
torch.Size([6, 2])


In [ ]:
# Sinus Values of Each Element of a Tensor

t8 = torch.sin(t7)
print(f"t8:\n{t8}\n")
print(f"t8.shape:\n{t8.shape}")

t8:
tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

t8.shape:
torch.Size([6, 2])


In [ ]:
# Changing the Shape of a Tensor

t9 = t8.reshape(3, 2, 2)
print(f"t9:\n{t9}\n")
print(f"t9.shape:\n{t9.shape}")

t9:
tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

t9.shape:
torch.Size([3, 2, 2])


In [ ]:
# Changing the Shape of a Tensor

t9 = t8.reshape(2, 3, 2)
print(f"t9:\n{t9}\n")
print(f"t9.shape:\n{t9.shape}")

t9:
tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894],
         [ 0.4121, -0.5440]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

t9.shape:
torch.Size([2, 3, 2])


In [ ]:
# Changing the Shape of a Tensor

t9 = t8.reshape(2, 2, 3)
print(f"t9:\n{t9}\n")
print(f"t9.shape:\n{t9.shape}")

t9:
tensor([[[-0.9589, -0.2794,  0.6570],
         [ 0.9894,  0.4121, -0.5440]],

        [[-0.9165, -0.9165, -0.9165],
         [-0.9165, -0.9165, -0.9165]]])

t9.shape:
torch.Size([2, 2, 3])
