In [ ]:
# Gradient Descent Example #

In [ ]:
# Increasing the Cell Width of Jupyter Notebook

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [ ]:
# Importing Libraries

import torch
from tqdm.auto import tqdm
import torch.nn as nn
import numpy as np

In [ ]:
# Creating a Dataset Which Shows Apple and Orange Yields with the Given Circumstances

# Input (Temperature, Rainfall, Humidity)
input = np.array([ [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [74, 66, 43],
                    [91, 87, 65],
                    [88, 134, 59],
                    [101, 44, 37],
                    [68, 96, 71],
                    [73, 66, 44],
                    [92, 87, 64],
                    [87, 135, 57],
                    [103, 43, 36],
                    [68, 97, 70] ], dtype='float32')

# Targets (Apples, Oranges)
target = np.array([ [56, 70],
                     [81, 101],
                     [119, 133],
                     [22, 37],
                     [103, 119],
                     [57, 69],
                     [80, 102],
                     [118, 132],
                     [21, 38],
                     [104, 118],
                     [57, 69],
                     [82, 100],
                     [118, 134],
                     [20, 38],
                     [102, 120] ], dtype='float32')

In [ ]:
# Converting Inputs and Targets to Tensors

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

print(f"inputs:\n{inputs}\n")
print(f"targets:\n{targets}\n")

inputs:
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

targets:
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])



In [ ]:
# Defining Weights & Biases with Kaiming Uniform Distribution and Loss Functions (MSE: Mean Square Error & MAE: Mean Absolute Error)

w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
nn.init.kaiming_uniform_(w)
nn.init.constant_(b, 0.)

print(w)
print(b)

def model(x):
    return x @ w.t() + b

def loss_mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

def loss_mae(t1, t2):
    diff = t1-t2
    return torch.sum(abs(diff))/diff.numel()

tensor([[ 0.8650,  0.4324, -0.4165],
        [-0.8620, -0.5538,  0.7566]], requires_grad=True)
tensor([0., 0.], requires_grad=True)


In [ ]:
# Generating Random Weights and Biases, Evaluating the Loss Value with MSE (Mean Square Error) Before Training

preds = model(inputs)
loss = loss_mse(preds, targets)
loss.backward()

print(f"loss:\n{loss}\n")
print(f"w:\n{w.detach().numpy()}\n")
print(f"w.grad:\n{w.grad}\n")
print(f"w/w.grad:\n{(w/w.grad).detach().numpy()}\n")
print(f"sum of w/w.grad:\n{torch.sum(w/w.grad)}")

loss:
16084.3466796875

w:
[[ 0.8650165   0.43242395 -0.41645873]
 [-0.8619659  -0.5537705   0.7566101 ]]

w.grad:
tensor([[  1276.2900,    155.3387,    238.3467],
        [-14368.6914, -15846.2227,  -9658.5811]])

w/w.grad:
[[ 6.7775859e-04  2.7837488e-03 -1.7472811e-03]
 [ 5.9989172e-05  3.4946530e-05 -7.8335535e-05]]

sum of w/w.grad:
0.001730826566927135


In [ ]:
# Training the Model

lr = 1e-4
epochs = 10000

for i in tqdm(range(epochs)):
    preds = model(inputs)
    loss = loss_mse(preds, targets)
    loss.backward()

    with torch.no_grad():
        w -= w.grad * lr
        b -= b.grad * lr
        w.grad.zero_()
        b.grad.zero_()

    if (i+1) % (3*epochs/5) == 0:   # After 60% of the Total Epoch Number;
        lr /= 10                    # Divide the Learning Rate by 10 (Optional).


print(f"Loss:\n{loss.item()}\n")
print(f"w:\n{w.detach().numpy()}\n")
print(f"w.grad:\n{w.grad}")

  0%|          | 0/10000 [00:00<?, ?it/s]

Loss:
1.0319154262542725

w:
[[-0.4046501   0.84179455  0.6995899 ]
 [-0.28593567  0.7921423   0.8886243 ]]

w.grad:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Generating Predictions After the Training

preds = model(inputs)

print(f"Inputs:\n{inputs.numpy()}\n")
print(f"Predictions:\n{torch.trunc(preds).detach().numpy()}\n")
print(f"Targets:\n{targets.numpy()}\n")
print(f"Difference:\n{(torch.trunc(preds)-targets).detach().numpy()}\n")
print(f"Loss:\n{loss_mse(preds, targets)}\n")

Inputs:
[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 74.  66.  43.]
 [ 91.  87.  65.]
 [ 88. 134.  59.]
 [101.  44.  37.]
 [ 68.  96.  71.]
 [ 73.  66.  44.]
 [ 92.  87.  64.]
 [ 87. 135.  57.]
 [103.  43.  36.]
 [ 68.  97.  70.]]

Predictions:
[[ 56.  70.]
 [ 82. 100.]
 [118. 132.]
 [ 20.  37.]
 [101. 118.]
 [ 55.  69.]
 [ 81. 100.]
 [118. 133.]
 [ 22.  38.]
 [102. 119.]
 [ 56.  70.]
 [ 80.  99.]
 [118. 132.]
 [ 19.  36.]
 [103. 119.]]

Targets:
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 57.  69.]
 [ 80. 102.]
 [118. 132.]
 [ 21.  38.]
 [104. 118.]
 [ 57.  69.]
 [ 82. 100.]
 [118. 134.]
 [ 20.  38.]
 [102. 120.]]

Difference:
[[ 0.  0.]
 [ 1. -1.]
 [-1. -1.]
 [-2.  0.]
 [-2. -1.]
 [-2.  0.]
 [ 1. -2.]
 [ 0.  1.]
 [ 1.  0.]
 [-2.  1.]
 [-1.  1.]
 [-2. -1.]
 [ 0. -2.]
 [-1. -2.]
 [ 1. -1.]]

Loss:
1.0319154262542725



In [ ]:
# Testing the Model with Single Input

i = 0
preds = model(inputs[i])

print(f"Inputs:\n{inputs[i].numpy()}\n")
print(f"Predictions:\n{torch.trunc(preds).detach().numpy()}\n")
print(f"Targets:\n{targets[i].numpy()}\n")
print(f"Difference:\n{(torch.trunc(preds)-targets[i]).detach().numpy()}\n")
print(f"Loss:\n{loss_mse(preds, targets[i])}\n")

Inputs:
[73. 67. 43.]

Predictions:
[56. 70.]

Targets:
[56. 70.]

Difference:
[0. 0.]

Loss:
0.5293396711349487

