In [ ]:
# Linear Regression Example #

In [ ]:
# Increasing the Cell Width of Jupyter Notebook

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [ ]:
# Importing Libraries

import torch
import numpy as np
import torch.nn as nn
from tqdm.auto import tqdm
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [ ]:
# Creating a Dataset Which Shows Apple and Orange Yields with the Given Circumstances:

# Inputs (Temperature, Rainfall, Humidity)
inputs = np.array([ [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [74, 66, 43],
                    [91, 87, 65],
                    [88, 134, 59],
                    [101, 44, 37],
                    [68, 96, 71],
                    [73, 66, 44],
                    [92, 87, 64],
                    [87, 135, 57],
                    [103, 43, 36],
                    [68, 97, 70] ], dtype='float32')

# Targets (Apples, Oranges)
targets = np.array([ [56, 70],
                     [81, 101],
                     [119, 133],
                     [22, 37],
                     [103, 119],
                     [57, 69],
                     [80, 102],
                     [118, 132],
                     [21, 38],
                     [104, 118],
                     [57, 69],
                     [82, 100],
                     [118, 134],
                     [20, 38],
                     [102, 120] ], dtype='float32')

In [ ]:
# Converting Inputs and Targets to Tensors

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(f"inputs:\n{inputs}\n")
print(f"targets:\n{targets}\n")

inputs:
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

targets:
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])



In [ ]:
# Defining Dataset

train_ds = TensorDataset(inputs, targets)
print(train_ds.tensors)

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]]))


In [ ]:
# Defining Data Loader

batch_size = 4
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
# Printing All the Input-Target Data Pieces per Batch

i = 1
for x_b, y_b in train_dl:
    print(f"inputs-batch-{i}:\n{x_b}\n")
    print(f"targets-batch-{i}:\n{y_b}\n")
    i += 1
    #break

inputs-batch-1:
tensor([[101.,  44.,  37.],
        [ 87., 135.,  57.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])

targets-batch-1:
tensor([[ 21.,  38.],
        [118., 134.],
        [119., 133.],
        [ 56.,  70.]])

inputs-batch-2:
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [103.,  43.,  36.]])

targets-batch-2:
tensor([[ 22.,  37.],
        [103., 119.],
        [102., 120.],
        [ 20.,  38.]])

inputs-batch-3:
tensor([[91., 88., 64.],
        [92., 87., 64.],
        [74., 66., 43.],
        [73., 66., 44.]])

targets-batch-3:
tensor([[ 81., 101.],
        [ 82., 100.],
        [ 57.,  69.],
        [ 57.,  69.]])

inputs-batch-4:
tensor([[ 91.,  87.,  65.],
        [ 68.,  96.,  71.],
        [ 88., 134.,  59.]])

targets-batch-4:
tensor([[ 80., 102.],
        [104., 118.],
        [118., 132.]])



In [ ]:
# Defining Model by nn.Linear() with Kaiming Uniform Distribution

model = nn.Linear(3, 2)
nn.init.kaiming_uniform_(model.weight)
if model.bias is not None:
    nn.init.constant_(model.bias, 0.)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5026, -0.0120,  1.2367],
        [-1.0853,  0.0381, -1.2989]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [ ]:
# Printing Parameters Quickly

list(model.parameters())

[Parameter containing:
 tensor([[ 0.5026, -0.0120,  1.2367],
         [-1.0853,  0.0381, -1.2989]], requires_grad=True),
 Parameter containing:
 tensor([0., 0.], requires_grad=True)]

In [ ]:
# Defining Loss Function

loss_fn = F.l1_loss
#loss_fn = F.mse_loss

In [ ]:
# Generating Predictions Before Training

preds = model(inputs)

print(f"Inputs:\n{inputs.numpy()}\n")
print(f"Predictions:\n{torch.trunc(preds).detach().numpy()}\n")
print(f"Targets:\n{targets.numpy()}\n")
print(f"Difference:\n{(torch.trunc(preds)-targets).detach().numpy()}\n")
print(f"Loss:\n{loss_fn(preds, targets)}\n")

Inputs:
[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 74.  66.  43.]
 [ 91.  87.  65.]
 [ 88. 134.  59.]
 [101.  44.  37.]
 [ 68.  96.  71.]
 [ 73.  66.  44.]
 [ 92.  87.  64.]
 [ 87. 135.  57.]
 [103.  43.  36.]
 [ 68.  97.  70.]]

Predictions:
[[  89. -132.]
 [ 123. -178.]
 [ 113. -164.]
 [  96. -157.]
 [ 120. -162.]
 [  89. -133.]
 [ 125. -179.]
 [ 115. -167.]
 [  95. -155.]
 [ 120. -162.]
 [  90. -133.]
 [ 124. -179.]
 [ 112. -163.]
 [  95. -156.]
 [ 119. -161.]]

Targets:
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 57.  69.]
 [ 80. 102.]
 [118. 132.]
 [ 21.  38.]
 [104. 118.]
 [ 57.  69.]
 [ 82. 100.]
 [118. 134.]
 [ 20.  38.]
 [102. 120.]]

Difference:
[[  33. -202.]
 [  42. -279.]
 [  -6. -297.]
 [  74. -194.]
 [  17. -281.]
 [  32. -202.]
 [  45. -281.]
 [  -3. -299.]
 [  74. -193.]
 [  16. -280.]
 [  33. -202.]
 [  42. -279.]
 [  -6. -297.]
 [  75. -194.]
 [  17. -281.]]

Loss:
142.9236297607422



In [ ]:
# Defining Optimizer

opt = torch.optim.SGD(model.parameters(), lr=1e-4)

In [ ]:
# Utility Function to Train the Model

def fit(epochs, model, loss_fn, opt, train_dl):

    lr_down = True
    for epoch in range(epochs):                       # For Each Epoch;

        for x_b, y_b in train_dl:                     # For Each Input-Target Data Piece per Batch;
            opt.zero_grad()                           # 1. Reset the Gradients to Zero
            pred = model(x_b)                         # 2. Generate Predictions
            loss = loss_fn(pred, y_b)                 # 3. Evaluate Loss
            loss.backward()                           # 4. Compute Gradients
            opt.step()                                # 5. Update Parameters Using Gradients

            if (epoch + 1) % (3 * epochs / 10) == 0:  # 6a. When It Reaches to 30% of the Total Epochs;
                if lr_down:
                    opt.param_groups[0]['lr'] /= 10   # 6b. Divide the Learning Rate by 10 for Once (Optional)
                lr_down = False

        if (epoch + 1) % 250 == 0:                    # 7. Print the Progress for a Specific Number of Epochs.
            print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}")


In [ ]:
# Training the Model with the Given Number of Epochs

fit(6000, model, loss_fn, opt, train_dl)

Epoch [250/6000], Loss: 2.4937
Epoch [500/6000], Loss: 7.3098
Epoch [750/6000], Loss: 3.7179
Epoch [1000/6000], Loss: 1.6053
Epoch [1250/6000], Loss: 0.8352
Epoch [1500/6000], Loss: 1.0063
Epoch [1750/6000], Loss: 0.9941
Epoch [2000/6000], Loss: 1.2181
Epoch [2250/6000], Loss: 0.7775
Epoch [2500/6000], Loss: 0.5395
Epoch [2750/6000], Loss: 1.3612
Epoch [3000/6000], Loss: 0.6276
Epoch [3250/6000], Loss: 0.6212
Epoch [3500/6000], Loss: 1.0177
Epoch [3750/6000], Loss: 0.6031
Epoch [4000/6000], Loss: 1.1869
Epoch [4250/6000], Loss: 0.9719
Epoch [4500/6000], Loss: 0.5462
Epoch [4750/6000], Loss: 0.8474
Epoch [5000/6000], Loss: 0.9824
Epoch [5250/6000], Loss: 0.5952
Epoch [5500/6000], Loss: 0.7583
Epoch [5750/6000], Loss: 0.7318
Epoch [6000/6000], Loss: 0.6711


In [ ]:
# Generating Predictions After Training

preds = model(inputs)

print(f"Inputs:\n{inputs.numpy()}\n")
print(f"Predictions:\n{torch.trunc(preds).detach().numpy()}\n")
print(f"Targets:\n{targets.numpy()}\n")
print(f"Difference:\n{(torch.trunc(preds)-targets).detach().numpy()}\n")
print(f"Loss:\n{loss_fn(preds, targets)}\n")

Inputs:
[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 74.  66.  43.]
 [ 91.  87.  65.]
 [ 88. 134.  59.]
 [101.  44.  37.]
 [ 68.  96.  71.]
 [ 73.  66.  44.]
 [ 92.  87.  64.]
 [ 87. 135.  57.]
 [103.  43.  36.]
 [ 68.  97.  70.]]

Predictions:
[[ 57.  70.]
 [ 82. 100.]
 [117. 132.]
 [ 21.  36.]
 [102. 118.]
 [ 55.  69.]
 [ 82. 100.]
 [118. 133.]
 [ 22.  38.]
 [103. 120.]
 [ 57.  70.]
 [ 81.  99.]
 [117. 132.]
 [ 19.  35.]
 [103. 119.]]

Targets:
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 57.  69.]
 [ 80. 102.]
 [118. 132.]
 [ 21.  38.]
 [104. 118.]
 [ 57.  69.]
 [ 82. 100.]
 [118. 134.]
 [ 20.  38.]
 [102. 120.]]

Difference:
[[ 1.  0.]
 [ 1. -1.]
 [-2. -1.]
 [-1. -1.]
 [-1. -1.]
 [-2.  0.]
 [ 2. -2.]
 [ 0.  1.]
 [ 1.  0.]
 [-1.  2.]
 [ 0.  1.]
 [-1. -1.]
 [-1. -2.]
 [-1. -3.]
 [ 1. -1.]]

Loss:
0.8251345157623291



In [ ]:
# Testing the Model with Single Input

i = 0
preds = model(inputs[i])

print(f"Inputs:\n{inputs[i].numpy()}\n")
print(f"Predictions:\n{torch.trunc(preds).detach().numpy()}\n")
print(f"Targets:\n{targets[i].numpy()}\n")
print(f"Difference:\n{(torch.trunc(preds)-targets[i]).detach().numpy()}\n")
print(f"Loss:\n{loss_fn(preds, targets[i])}\n")

Inputs:
[73. 67. 43.]

Predictions:
[57. 70.]

Targets:
[56. 70.]

Difference:
[1. 0.]

Loss:
0.6847705841064453

